// get DOM elements
const body = document.getElementById('gameBody');
const info = document.getElementById('info');
const buttons = document.querySelectorAll('button');
let gameOver = false;

// AAAAAAAAAAAAAAAHHHHHHH
const winMoves = [
    [11,21,31],
    [12,22,32],
    [13,23,33],
    [11,12,13],
    [21,22,23],
    [31,32,33],
    [11,22,33],
    [13,22,31]
];

let Xturf = [];
let Oturf = [];

// initially render the buttons
for (let y = 1; y <= 3; y++) {
    for (let x = 1; x <= 3; x++) {
        body.innerHTML +=
        `<button id="${x}${y}" class="gameButton">~</button>`;
    }
    body.innerHTML += '<br>';
}

let currentPlayer = 'X';

// this function was generated by chatgpt
function hasWon(turf) {
    for (const winMove of winMoves) {
        if (winMove.every(cell => turf.includes(cell.toString()))) {
            return true;
        }
    }
    return false;
}
//

function stopGame() {
    gameOver = true;
}

function updateInfo() {
    info.innerText = `${currentPlayer}'s turn`;
    if (hasWon(Xturf)) {info.innerText = 'X has won!'; stopGame();
    document.body.style.backgroundColor = 'lightcoral';}
    else if (hasWon(Oturf)) {info.innerText = 'O has won!'; stopGame();
    document.body.style.backgroundColor = 'lightblue';}
    if (!gameOver && ((Xturf.length + Oturf.length) == 9)) {
        info.innerText = "It's a tie!";
        document.body.style.backgroundColor = 'grey';
    }
}

document.body.addEventListener('click', function(event) {
     if ((event.target.tagName === 'BUTTON') && !gameOver) {
        if ((event.target.textContent !== 'X') && (event.target.textContent !== 'O')) {
            event.target.textContent = currentPlayer;
            if (currentPlayer == 'X') {
                event.target.style.backgroundColor = 'red';
                Xturf.push(event.target.id);
                currentPlayer = 'O';
            } else {
                event.target.style.backgroundColor = 'blue';
                Oturf.push(event.target.id);
                currentPlayer = 'X';
            }
            updateInfo();
        }
     }
})

updateInfo();